global:
  imageRegistry: "969446871231.dkr.ecr.us-east-2.amazonaws.com"
  imagePullSecrets: []
  imageTag: "latest"
services:
  adservice:
    image:
      repository: 969446871231.dkr.ecr.us-east-2.amazonaws.com/adservice
      tag: "4ebdad6cd6643b337fe28ac03094da3f8bdf4812"
    port: 9555
    resources:
      requests:
        cpu: 200m
        memory: 180Mi
      limits:
        cpu: 300m
        memory: 300Mi
  cartservice:
    image:
      repository: 969446871231.dkr.ecr.us-east-2.amazonaws.com/cartservice
      tag: "5d507dab45a0ebb0cfbf2ff61f093b6c2ea82f60"
    port: 7070
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
  checkoutservice:
    image:
      repository: 969446871231.dkr.ecr.us-east-2.amazonaws.com/checkoutservice
      tag: "c5e3da8ce2a1d25df60a189be4fb80a0068f9852"
    port: 5050
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  currencyservice:
    image:
      repository: 969446871231.dkr.ecr.us-east-2.amazonaws.com/currencyservice
      tag: "9dbf2f87b4d8896db9f2391276f3e0f8f3b8c48f"
    port: 7000
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  emailservice:
    image:
      repository: 969446871231.dkr.ecr.us-east-2.amazonaws.com/emailservice
      tag: "42f5893e3638f76e1314e2763fc1bf7937beddd8"
    port: 8080
    servicePort: 5000
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  frontend:
    image:
      repository: 969446871231.dkr.ecr.us-east-2.amazonaws.com/frontend
      tag: "25a82db18fd295d72b7010e837b93ea2cb4a3018"
    port: 8080
    serviceType: ClusterIP
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
  loadgenerator:
    image:
      repository: 969446871231.dkr.ecr.us-east-2.amazonaws.com/loadgeneratorservice
      tag: "77fd6bbbeb60a3848601370147504e9e0936efa3"
    replicas: 1
    users: "10"
    rate: "1"
    resources:
      requests:
        cpu: 300m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  paymentservice:
    image:
      repository: 969446871231.dkr.ecr.us-east-2.amazonaws.com/paymentservice
      tag: "9094375210ac16360bbcff448625d19345e35bf8"
    port: 50051
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  productcatalogservice:
    image:
      repository: 969446871231.dkr.ecr.us-east-2.amazonaws.com/productcatalogservice
      tag: "f388e00aa36e9ba772bc04f66002eb2785146cd5"
    port: 3550
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  recommendationservice:
    image:
      repository: 969446871231.dkr.ecr.us-east-2.amazonaws.com/recommendationservice
      tag: "4486cdca7aabc9976d6dd43d463c29af6053ffd5"
    port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 220Mi
      limits:
        cpu: 200m
        memory: 450Mi
  shippingservice:
    image:
      repository: 969446871231.dkr.ecr.us-east-2.amazonaws.com/shippingservice
      tag: "b2f151acccd746eb14514aa0efdb679daf021e69"
    port: 50051
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
redis:
  image: redis:alpine
  port: 6379
  resources:
    requests:
      cpu: 70m
      memory: 200Mi
    limits:
      cpu: 125m
      memory: 256Mi
securityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
dockerregistry:
  enabled: false
ingress:
  enabled: true
  name: online-boutique
  className: alb
  scheme: internet-facing
  targetType: ip
  certificateArn: "arn:aws:acm:us-east-2:969446871231:certificate/a5f54647-1a3d-458f-a129-8598b6e5f049"
  listenPorts: '[{"HTTP": 80}, {"HTTPS": 443}]'
  sslRedirect: "443"
  groupName: online-boutique
  host: online-boutique.f3techglobal.online
